// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webResfulAPIs.Models;

#nullable disable

namespace webResfulAPIs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428161908_CategoryAndCreators")]
    partial class CategoryAndCreators
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webResfulAPIs.Models.BoardGameCategory", b =>
                {
                    b.Property<Guid>("BoardGame_Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("boardgame_id");

                    b.Property<int>("Category_Id")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("Created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("Updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("BoardGame_Id", "Category_Id");

                    b.HasIndex("Category_Id");

                    b.ToTable("BoardGameCategories", (string)null);
                });

            modelBuilder.Entity("webResfulAPIs.Models.BoardGameCreators", b =>
                {
                    b.Property<Guid>("Creator_Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("creator_id");

                    b.Property<Guid>("BoardGame_Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("boardgame_id");

                    b.Property<DateTime>("Created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("Updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Creator_Id", "BoardGame_Id");

                    b.HasIndex("BoardGame_Id");

                    b.ToTable("BoardGameCreators", (string)null);
                });

            modelBuilder.Entity("webResfulAPIs.Models.BoardGameDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BoardGame_Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bg_id");

                    b.Property<DateTime>("Created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Full_Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("")
                        .HasColumnName("full_description");

                    b.Property<string>("Short_Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("")
                        .HasColumnName("short_description");

                    b.Property<DateTime>("Updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("BoardGame_Id")
                        .IsUnique();

                    b.ToTable("BoardGameDescription", (string)null);
                });

            modelBuilder.Entity("webResfulAPIs.Models.BoardGameImages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Alt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("")
                        .HasColumnName("alt");

                    b.Property<Guid>("Bg_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bg_id");

                    b.Property<DateTime>("Created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Img_Url")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("")
                        .HasColumnName("img_url");

                    b.Property<bool>("Is_Thumbnail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_thumbnail");

                    b.Property<DateTime>("Updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Bg_id");

                    b.ToTable("BoardGameImages", (string)null);
                });

            modelBuilder.Entity("webResfulAPIs.Models.BoardGames", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("Age_Requirement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("age_requirement");

                    b.Property<decimal>("Base_Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("base_price");

                    b.Property<decimal>("Complexity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("complexity");

                    b.Property<DateTime>("Created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Max_Player")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("max_player");

                    b.Property<int>("Max_Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("max_time");

                    b.Property<int>("Min_Player")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("min_player");

                    b.Property<int>("Min_Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("min_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("")
                        .HasColumnName("name");

                    b.Property<int>("Prefer_Player")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("prefer_player");

                    b.Property<decimal>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("rating");

                    b.Property<decimal>("Size_X")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("size_x");

                    b.Property<decimal>("Size_Y")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("size_y");

                    b.Property<decimal>("Size_Z")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("size_z");

                    b.Property<int>("Sold_Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sold_quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<int>("Stock_Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("stock_quantity");

                    b.Property<DateTime>("Updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.ToTable("BoardGames", null, t =>
                        {
                            t.HasCheckConstraint("CK_BoardGames_Age", "age_requirement >= 0");

                            t.HasCheckConstraint("CK_BoardGames_Prefer", "prefer_player >= 0");

                            t.HasCheckConstraint("CK_BoardGames_Price", "base_price >= 0");

                            t.HasCheckConstraint("CK_BoardGames_Rating", "rating >= 0 and rating <=10");

                            t.HasCheckConstraint("CK_BoardGames_SizeX", "size_x >= 0");

                            t.HasCheckConstraint("CK_BoardGames_SizeY", "size_y >= 0");

                            t.HasCheckConstraint("CK_BoardGames_SizeZ", "size_z >= 0");

                            t.HasCheckConstraint("CK_BoardGames_Sold", "sold_quantity >= 0");

                            t.HasCheckConstraint("CK_BoardGames_Stock", "stock_quantity >= 0");

                            t.HasCheckConstraint("CK_BoardGames_ValidPlayer", "max_player >= min_player and min_player >=0");

                            t.HasCheckConstraint("CK_BoardGames_ValidTime", "max_time >= min_time and min_time >=0");

                            t.HasCheckConstraint("CK_BoardGames_Weight", "weight >= 0");
                        });
                });

            modelBuilder.Entity("webResfulAPIs.Models.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime>("Updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Category_Status", "status IN ('Active', 'Inactive', 'Banned')");
                        });
                });

            modelBuilder.Entity("webResfulAPIs.Models.Creators", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("")
                        .HasColumnName("bio");

                    b.Property<DateTime>("Created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("empty")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Author")
                        .HasColumnName("type");

                    b.Property<DateTime>("Updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.ToTable("Creators", null, t =>
                        {
                            t.HasCheckConstraint("CK_Creators_Status", "status IN ('Active', 'Inactive', 'OutStock')");

                            t.HasCheckConstraint("CK_Creators_Type", "type IN ('Active','Inactive','Banned')");
                        });
                });

            modelBuilder.Entity("webResfulAPIs.Models.Profiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("address");

                    b.Property<DateTime>("Birth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("dateTime")
                        .HasDefaultValue(new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified))
                        .HasColumnName("birth");

                    b.Property<DateTime>("Created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("dateTime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Display_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Full_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Male")
                        .HasColumnName("gender");

                    b.Property<string>("Image_Url")
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("img_url");

                    b.Property<DateTime>("Updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("dateTime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("User_Id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("User_Id")
                        .IsUnique()
                        .HasDatabaseName("IX_Profiles_User_Id");

                    b.ToTable("Profiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Profiles_Gender", "gender IN ('Male','Female','Others')");
                        });
                });

            modelBuilder.Entity("webResfulAPIs.Models.RefreshTokens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Created_by_ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("Expired_date")
                        .HasColumnType("datetime")
                        .HasColumnName("expired_date");

                    b.Property<bool>("Is_revoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("token");

                    b.Property<int>("User_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_Token");

                    b.HasIndex("User_id");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("webResfulAPIs.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("Deleted_at")
                        .HasColumnType("DateTime")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("Email_verify")
                        .HasColumnType("DateTime")
                        .HasColumnName("email_verify");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Public_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("public_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime>("Updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Phone")
                        .HasFilter("[phone] IS NOT NULL");

                    b.HasIndex("Public_id")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Public_id");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "role IN ('Admin','Users','Staff')");

                            t.HasCheckConstraint("CK_Users_Status", "status IN ('Active','Inactive','Pending','Banned')");
                        });
                });

            modelBuilder.Entity("webResfulAPIs.Models.BoardGameCategory", b =>
                {
                    b.HasOne("webResfulAPIs.Models.BoardGames", "BoardGame")
                        .WithMany("BoardGameCategories")
                        .HasForeignKey("BoardGame_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webResfulAPIs.Models.Categories", "Category")
                        .WithMany("BoardGameCategories")
                        .HasForeignKey("Category_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardGame");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("webResfulAPIs.Models.BoardGameCreators", b =>
                {
                    b.HasOne("webResfulAPIs.Models.BoardGames", "BoardGame")
                        .WithMany("BoardGameCreators")
                        .HasForeignKey("BoardGame_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webResfulAPIs.Models.Creators", "Creator")
                        .WithMany("BoardGameCreators")
                        .HasForeignKey("Creator_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardGame");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("webResfulAPIs.Models.BoardGameDescription", b =>
                {
                    b.HasOne("webResfulAPIs.Models.BoardGames", "BoardGames")
                        .WithOne()
                        .HasForeignKey("webResfulAPIs.Models.BoardGameDescription", "BoardGame_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BoardGames");
                });

            modelBuilder.Entity("webResfulAPIs.Models.BoardGameImages", b =>
                {
                    b.HasOne("webResfulAPIs.Models.BoardGames", "BoardGame")
                        .WithMany("BoardGameImages")
                        .HasForeignKey("Bg_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BoardGame");
                });

            modelBuilder.Entity("webResfulAPIs.Models.Profiles", b =>
                {
                    b.HasOne("webResfulAPIs.Models.Users", "User")
                        .WithOne()
                        .HasForeignKey("webResfulAPIs.Models.Profiles", "User_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("webResfulAPIs.Models.RefreshTokens", b =>
                {
                    b.HasOne("webResfulAPIs.Models.Users", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("webResfulAPIs.Models.BoardGames", b =>
                {
                    b.Navigation("BoardGameCategories");

                    b.Navigation("BoardGameCreators");

                    b.Navigation("BoardGameImages");
                });

            modelBuilder.Entity("webResfulAPIs.Models.Categories", b =>
                {
                    b.Navigation("BoardGameCategories");
                });

            modelBuilder.Entity("webResfulAPIs.Models.Creators", b =>
                {
                    b.Navigation("BoardGameCreators");
                });

            modelBuilder.Entity("webResfulAPIs.Models.Users", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
