// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webResfulAPIs.Models;

#nullable disable

namespace webResfulAPIs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422175410_RefreshTable")]
    partial class RefreshTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webResfulAPIs.Models.Profiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("address");

                    b.Property<DateTime>("Birth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("dateTime")
                        .HasDefaultValue(new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified))
                        .HasColumnName("birth");

                    b.Property<DateTime>("Created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("dateTime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Display_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Full_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Male")
                        .HasColumnName("gender");

                    b.Property<string>("Image_Url")
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("img_url");

                    b.Property<DateTime>("Updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("dateTime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("User_Id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("User_Id")
                        .IsUnique()
                        .HasDatabaseName("IX_Profiles_User_Id");

                    b.ToTable("Profiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Profiles_Gender", "gender IN ('Male','Female','Others')");
                        });
                });

            modelBuilder.Entity("webResfulAPIs.Models.RefreshTokens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Created_by_ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("Expired_date")
                        .HasColumnType("datetime")
                        .HasColumnName("expired_date");

                    b.Property<bool>("Is_revoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("token");

                    b.Property<int>("User_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_Token");

                    b.HasIndex("User_id");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("webResfulAPIs.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("Deleted_at")
                        .HasColumnType("DateTime")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("Email_verify")
                        .HasColumnType("DateTime")
                        .HasColumnName("email_verify");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Public_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("public_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime>("Updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Phone")
                        .HasFilter("[phone] IS NOT NULL");

                    b.HasIndex("Public_id")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Public_id");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "role IN ('Admin','Users','Staff')");

                            t.HasCheckConstraint("CK_Users_Status", "status IN ('Active','Inactive','Pending','Banned')");
                        });
                });

            modelBuilder.Entity("webResfulAPIs.Models.Profiles", b =>
                {
                    b.HasOne("webResfulAPIs.Models.Users", "User")
                        .WithOne()
                        .HasForeignKey("webResfulAPIs.Models.Profiles", "User_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("webResfulAPIs.Models.RefreshTokens", b =>
                {
                    b.HasOne("webResfulAPIs.Models.Users", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("webResfulAPIs.Models.Users", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
